name: Scheduled ATB Request

on:
  schedule:
    - cron: '0 23 * * 0'  
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-atb-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r FutureYou/requirements.txt

      - name: Run ATB Request Script
        working-directory: FutureYou
        run: |
          python atbRequest.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
