name: Scheduled FutureYou Reports

on:
  workflow_dispatch:
    inputs:
      name:
        description: "User's name"
        required: true
      email:
        description: "User's email"
        required: true

jobs:
  run-atb-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r FutureYou/requirements.txt

      - name: Run ATB Request Script
        working-directory: FutureYou
        env:
          # 🔹 Secrets (These remain unchanged)
          GH_PAT: ${{ secrets.GH_PAT }}

          EMAIL_SENDER_GMAIL: ${{ secrets.EMAIL_SENDER_GMAIL }}
          EMAIL_PASSWORD_GMAIL: ${{ secrets.EMAIL_PASSWORD_GMAIL }}

          FUTUREYOU_CONTRACTING_CLIENT_ID: ${{ secrets.FUTUREYOU_CONTRACTING_CLIENT_ID }}
          FUTUREYOU_CONTRACTING_CLIENT_SECRET: ${{ secrets.FUTUREYOU_CONTRACTING_CLIENT_SECRET }}

          FUTUREYOU_RECRUITMENT_CLIENT_ID: ${{ secrets.FUTUREYOU_RECRUITMENT_CLIENT_ID }}
          FUTUREYOU_RECRUITMENT_CLIENT_SECRET: ${{ secrets.FUTUREYOU_RECRUITMENT_CLIENT_SECRET }}

          # 🔹 Variables (Now using GitHub Variables instead of Secrets)
          XERO_REFRESH_TOKEN_FUTUREYOU_CONTRACTING: ${{ vars.XERO_REFRESH_TOKEN_FUTUREYOU_CONTRACTING }}
          XERO_REFRESH_TOKEN_FUTUREYOU_RECRUITMENT: ${{ vars.XERO_REFRESH_TOKEN_FUTUREYOU_RECRUITMENT }}
        run: |
          python atbRequest.py ${{ github.event.inputs.name }} ${{ github.event.inputs.email }}
          python overdueRequest.py ${{ github.event.inputs.name }} ${{ github.event.inputs.email }}
